const cron = require('node-cron');
const Project = require('../models/Project');
const Task = require('../models/Task');
const TimeLog = require('../models/TimeLog');
const { sendClientReportEmail } = require('../services/emailService');

// Schedule to run every Friday at 5:00 PM ('0 17 * * 5')
// For testing purposes right now, you can change it to run every minute: '* * * * *'
cron.schedule('0 17 * * 5', async () => {
  console.log('Running automated weekly client reports...');

  try {
    // 1. Find all projects that have reporting enabled and a valid client email
    const activeProjects = await Project.find({
      sendWeeklyReports: true,
      clientEmail: { $ne: null }
    });

    // Get the date exactly 7 days ago
    const oneWeekAgo = new Date();
    oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);

    for (const project of activeProjects) {
      // 2. Fetch Deliverable Tasks completed in the last 7 days
      const completedTasks = await Task.find({
        projectId: project._id,
        status: { $in: ['Done', 'Completed'] },
        updatedAt: { $gte: oneWeekAgo },
        isClientDeliverable: true // Only show them what they are meant to see
      });

      // 3. Aggregate Time Logged in the last 7 days
      const recentTimeLogs = await TimeLog.find({
        projectId: project._id,
        createdAt: { $gte: oneWeekAgo }
      });

      const totalMinutes = recentTimeLogs.reduce((acc, log) => acc + log.durationMinutes, 0);
      const totalHours = (totalMinutes / 60).toFixed(1);

      // 4. Skip emailing if there was absolutely no activity this week
      if (completedTasks.length === 0 && totalMinutes === 0) {
        continue;
      }

      // 5. Generate the White-labeled HTML Email
      const htmlTemplate = `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
          <div style="background-color: #1a1c26; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
            <h1 style="color: #ffffff; margin: 0;">Weekly Project Briefing</h1>
            <p style="color: #7c7fff; margin: 5px 0 0 0;">Project: ${project.title}</p>
          </div>
          
          <div style="padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
            <p style="font-size: 16px;">Hello,</p>
            <p style="font-size: 16px; color: #4b5563;">Here is your automated weekly progress update for the past 7 days.</p>
            
            <div style="background-color: #f3f4f6; padding: 15px; rounded-lg; margin: 20px 0; border-left: 4px solid #7c7fff;">
              <h3 style="margin: 0 0 10px 0; color: #111827;">⏱️ Time Tracked This Week</h3>
              <p style="font-size: 24px; font-weight: bold; margin: 0; color: #7c7fff;">${totalHours} Hours</p>
            </div>

            <h3 style="color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 5px;">✅ Completed Deliverables</h3>
            ${completedTasks.length > 0 ? `
              <ul style="padding-left: 20px; color: #4b5563;">
                ${completedTasks.map(task => `
                  <li style="margin-bottom: 8px;">
                    <strong>${task.title}</strong>
                    ${task.description ? `<br><span style="font-size: 13px; color: #6b7280;">${task.description}</span>` : ''}
                  </li>
                `).join('')}
              </ul>
            ` : '<p style="color: #6b7280; font-style: italic;">No major deliverables were marked as complete this week.</p>'}
            
            <p style="margin-top: 30px; font-size: 14px; color: #9ca3af;">
              This is an automated message generated by ProjectSphere. If you have questions, please reach out to your project manager.
            </p>
          </div>
        </div>
      `;

      // 6. Dispatch the email
      await sendClientReportEmail(
        project.clientEmail, 
        `Weekly Update: ${project.title}`, 
        htmlTemplate
      );
    }

  } catch (error) {
    console.error('Error running weekly report cron job:', error);
  }
});